//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_De_Ropa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pantalone
    {
        public int id_Pantalon { get; set; }
        public string Marca { get; set; }
        public Nullable<int> Talle { get; set; }
        public string Modelo { get; set; }
        public string Material { get; set; }
        public string Color { get; set; }
        public string Estilo { get; set; }
    }
}
