//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_De_Ropa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tienda_De_RopaEntities : DbContext
    {
        public Tienda_De_RopaEntities()
            : base("name=Tienda_De_RopaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buzo> Buzos { get; set; }
        public virtual DbSet<Pantalone> Pantalones { get; set; }
        public virtual DbSet<Remera> Remeras { get; set; }
        public virtual DbSet<Zapatilla> Zapatillas { get; set; }
    }
}
